# azure-pipelines.yml
trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      options: '-B'
    displayName: 'Build with Maven'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/target/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Build Artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
